import { motion } from 'framer-motion';
import { useLanguage } from '../i18n';

const content = {
  id: { title: 'Panduan Penggunaan', intro: 'Gunakan alat ini hanya untuk website yang Anda miliki atau memiliki izin untuk diuji.', start: 'Memulai', steps: ['Masukkan URL publik dengan HTTPS.', 'Pilih mode pengujian sesuai tujuan.', 'Mulai dengan 1 kunjungan dan batch kecil.', 'Pantau progress, hasil, dan error secara real-time.'], modes: [['🛡️ Mode Stealth', 'Pengujian kompatibilitas browser dengan interaksi yang lebih lengkap.', ['Navigasi dan JavaScript aktif', 'Simulasi scroll, mouse, dan fokus halaman', 'Cocok untuk QA dan pemeriksaan analytics']], ['⚡ Mode Storm', 'Uji beban terbatas pada sistem milik sendiri.', ['Prioritas pada kecepatan', 'Concurrency lebih tinggi memakai lebih banyak RAM', 'Gunakan hanya pada staging atau jadwal load test']], ['🔍 Mode Search Engine', 'Memeriksa alur hasil pencarian untuk domain yang sudah terindeks.', ['Memilih Google, Bing, atau DuckDuckGo', 'Mencari dan memvalidasi link domain', 'Bisa gagal jika CAPTCHA atau hasil tidak tersedia']]], tips: 'Praktik terbaik', tipsList: ['Mulai dari 1–3 kunjungan.', 'Gunakan batch 1–3 untuk server lokal.', 'Pastikan domain publik dan DNS aktif.', 'Jangan gunakan untuk memanipulasi traffic, iklan, atau analytics pihak lain.'], troubleshooting: 'Pemecahan masalah', problems: [['Search gagal', 'Pastikan domain muncul saat dicari manual dan periksa log engine.'], ['Browser gagal dibuka', 'Pastikan Chromium Playwright terpasang dan RAM mencukupi.'], ['Hasil analytics tidak sesuai', 'Lokasi GA4 terutama berasal dari IP publik, bukan timezone browser.']] },
  en: { title: 'Usage Guide', intro: 'Use this tool only for websites you own or are authorized to test.', start: 'Getting started', steps: ['Enter a public HTTPS URL.', 'Choose a mode for your test objective.', 'Start with 1 visit and a small batch.', 'Monitor progress, results, and errors in real time.'], modes: [['🛡️ Stealth mode', 'Browser compatibility testing with richer interaction coverage.', ['Navigation and JavaScript enabled', 'Scroll, mouse, and focus simulation', 'Useful for QA and analytics checks']], ['⚡ Storm mode', 'Limited load testing for systems you control.', ['Prioritizes speed', 'Higher concurrency uses more RAM', 'Use only on staging or scheduled load tests']], ['🔍 Search Engine mode', 'Checks the search-result flow for an indexed domain.', ['Selects Google, Bing, or DuckDuckGo', 'Finds and validates the domain link', 'Can fail on CAPTCHA or unavailable results']]], tips: 'Best practices', tipsList: ['Start with 1–3 visits.', 'Use batch 1–3 on local servers.', 'Make sure DNS and the public domain are active.', 'Do not use it to manipulate third-party traffic, ads, or analytics.'], troubleshooting: 'Troubleshooting', problems: [['Search fails', 'Confirm the domain appears in a manual search and inspect the engine log.'], ['Browser fails to launch', 'Ensure Playwright Chromium is installed and enough RAM is available.'], ['Analytics location is unexpected', 'GA4 primarily uses public IP location, not the browser timezone.']] },
  es: { title: 'Guía de uso', intro: 'Usa esta herramienta solo en sitios propios o autorizados.', start: 'Primeros pasos', steps: ['Introduce una URL HTTPS pública.', 'Elige el modo según tu objetivo.', 'Empieza con 1 visita y un lote pequeño.', 'Supervisa el progreso y los errores en tiempo real.'], modes: [['🛡️ Modo Stealth', 'Pruebas de compatibilidad con más interacciones.', ['Navegación y JavaScript activos', 'Simulación de scroll, ratón y foco', 'Útil para QA y analytics']], ['⚡ Modo Storm', 'Pruebas de carga limitadas en sistemas propios.', ['Prioriza la velocidad', 'Más concurrencia usa más RAM', 'Usa solo staging o pruebas programadas']], ['🔍 Modo Search Engine', 'Comprueba el flujo de resultados de un dominio indexado.', ['Usa Google, Bing o DuckDuckGo', 'Valida el enlace del dominio', 'Puede fallar con CAPTCHA']]], tips: 'Buenas prácticas', tipsList: ['Empieza con 1–3 visitas.', 'Usa lotes de 1–3 en local.', 'Comprueba DNS y el dominio público.', 'No manipules tráfico, anuncios o analytics de terceros.'], troubleshooting: 'Solución de problemas', problems: [['Falla la búsqueda', 'Comprueba el dominio manualmente y revisa los logs.'], ['No inicia el navegador', 'Instala Chromium de Playwright y verifica la RAM.'], ['Ubicación de analytics incorrecta', 'GA4 usa principalmente la IP pública, no la zona horaria.']] },
  fr: { title: "Guide d'utilisation", intro: 'Utilisez cet outil uniquement sur des sites autorisés.', start: 'Démarrage', steps: ['Saisissez une URL HTTPS publique.', 'Choisissez le mode adapté.', 'Commencez avec 1 visite et un petit lot.', 'Suivez la progression et les erreurs en direct.'], modes: [['🛡️ Mode Stealth', 'Tests de compatibilité avec davantage d’interactions.', ['Navigation et JavaScript actifs', 'Simulation du défilement et de la souris', 'Utile pour QA et analytics']], ['⚡ Mode Storm', 'Tests de charge limités sur vos systèmes.', ['Priorité à la vitesse', 'Plus de concurrence utilise plus de RAM', 'Utilisez staging ou des tests planifiés']], ['🔍 Mode Search Engine', 'Vérifie le parcours de recherche d’un domaine indexé.', ['Google, Bing ou DuckDuckGo', 'Validation du lien du domaine', 'Peut échouer avec un CAPTCHA']]], tips: 'Bonnes pratiques', tipsList: ['Commencez par 1–3 visites.', 'Utilisez un lot de 1–3 en local.', 'Vérifiez DNS et le domaine public.', 'Ne manipulez pas les analytics ou publicités de tiers.'], troubleshooting: 'Dépannage', problems: [['La recherche échoue', 'Vérifiez le domaine manuellement et consultez les logs.'], ['Le navigateur ne démarre pas', 'Installez Chromium Playwright et vérifiez la RAM.'], ['Localisation analytics incorrecte', 'GA4 utilise surtout l’IP publique, pas le fuseau horaire.']] },
  de: { title: 'Bedienungsanleitung', intro: 'Verwenden Sie dieses Tool nur für eigene oder autorisierte Websites.', start: 'Erste Schritte', steps: ['Geben Sie eine öffentliche HTTPS-URL ein.', 'Wählen Sie den passenden Modus.', 'Beginnen Sie mit 1 Besuch und einem kleinen Stapel.', 'Überwachen Sie Fortschritt und Fehler in Echtzeit.'], modes: [['🛡️ Stealth-Modus', 'Browser-Kompatibilität mit umfangreicheren Interaktionen.', ['Navigation und JavaScript aktiv', 'Scroll-, Maus- und Fokus-Simulation', 'Geeignet für QA und Analytics']], ['⚡ Storm-Modus', 'Begrenzte Lasttests für eigene Systeme.', ['Geschwindigkeit im Vordergrund', 'Mehr Parallelität benötigt mehr RAM', 'Nur Staging oder geplante Tests']], ['🔍 Search-Engine-Modus', 'Prüft Suchergebnisse für eine indexierte Domain.', ['Google, Bing oder DuckDuckGo', 'Domain-Link wird validiert', 'Kann bei CAPTCHA fehlschlagen']]], tips: 'Bewährte Methoden', tipsList: ['Mit 1–3 Besuchen starten.', 'Lokal Stapelgröße 1–3 verwenden.', 'DNS und öffentliche Domain prüfen.', 'Keinen Traffic, Anzeigen oder Analytics Dritter manipulieren.'], troubleshooting: 'Fehlerbehebung', problems: [['Suche schlägt fehl', 'Domain manuell prüfen und Logs ansehen.'], ['Browser startet nicht', 'Playwright Chromium installieren und RAM prüfen.'], ['Falscher Analytics-Standort', 'GA4 nutzt hauptsächlich die öffentliche IP, nicht die Zeitzone.']] }
};

export default function UsageGuide() {
  const { language } = useLanguage();
  const c = content[language] || content.en;
  return <motion.section initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="mt-16 mb-8 rounded-3xl border border-white/10 bg-slate-900/60 p-6 shadow-2xl backdrop-blur-md sm:p-8">
    <h2 className="mb-3 text-center text-3xl font-bold text-transparent bg-gradient-to-r from-purple-300 to-pink-300 bg-clip-text">📖 {c.title}</h2>
    <p className="mx-auto mb-8 max-w-3xl text-center text-sm text-slate-300">{c.intro}</p>
    <div className="mb-8 rounded-2xl border border-violet-400/20 bg-violet-500/10 p-5"><h3 className="mb-3 text-xl font-semibold text-violet-200">🚀 {c.start}</h3><ol className="grid gap-3 text-sm text-slate-300 md:grid-cols-2">{c.steps.map((x, i) => <li key={x} className="flex gap-3"><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-violet-500/30 text-xs font-bold text-violet-200">{i + 1}</span>{x}</li>)}</ol></div>
    <div className="grid gap-5 lg:grid-cols-3">{c.modes.map(([title, desc, list], i) => <article key={title} className={`rounded-2xl border p-5 ${['border-indigo-500/40 bg-indigo-950/40', 'border-orange-500/40 bg-orange-950/40', 'border-cyan-500/40 bg-cyan-950/40'][i]}`}><h3 className="mb-2 text-lg font-semibold text-white">{title}</h3><p className="mb-4 text-sm text-slate-300">{desc}</p><ul className="space-y-2 text-sm text-slate-300">{list.map(x => <li key={x}>✓ {x}</li>)}</ul></article>)}</div>
    <div className="mt-5 grid gap-5 md:grid-cols-2"><article className="rounded-2xl border border-emerald-500/30 bg-emerald-950/30 p-5"><h3 className="mb-3 text-lg font-semibold text-emerald-200">💡 {c.tips}</h3><ul className="space-y-2 text-sm text-slate-300">{c.tipsList.map(x => <li key={x}>• {x}</li>)}</ul></article><article className="rounded-2xl border border-amber-500/30 bg-amber-950/30 p-5"><h3 className="mb-3 text-lg font-semibold text-amber-200">🔧 {c.troubleshooting}</h3><div className="space-y-3 text-sm text-slate-300">{c.problems.map(([q, a]) => <div key={q}><strong className="text-amber-100">{q}</strong><p>{a}</p></div>)}</div></article></div>
  </motion.section>;
}
